version: "3.6"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

    networks:
      - djangonetwork

  db:
    image: postgres
    networks:
      - djangonetwork
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
      djangonetwork:
        driver: bridge