# Generated by Django 3.2.12 on 2022-03-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboardapi', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
